### ISSUE TITLE
Design a new logo for the application

### ISSUE THREAD

**Issue by dilpreetsio** [geekyd/know-your-frontend#6]
Add a new logo of sizes 16x16,32x32,48x48, 128x128

name the icons as icon16, icon32, icon48 & icon128

**Comment by khushmeen** [comment]
I can work on this one

**Comment by dilpreetsio** [comment]
Sure please go ahead @khushmeen

**Comment by lbonillaii** [comment]
Any logo? @geekyd

**Comment by dilpreetsio** [comment]
@lbonillaii Please feel free to open/take up other issue.
